# -*- coding: utf-8 -*-
"""
Source data for 凡亞's poetry collection.
Edit this file to add, remove, or revise poems, then run `python3 generate.py`
from the website/ directory to rebuild the site.

Each poem is a dict:
  slug        - url-safe filename (no spaces), used as poems/<slug>.html
  title       - poem title, exactly as written
  subtitle    - optional dedication/subtitle line (e.g. "——给 S.F."), or None
  epigraph    - optional {"lines": [...], "attribution": "..."} or None
  parts       - list of {"label": "1." / "一" / None, "lines": [...]}
                use "" for a stanza break, and a lone "&" line for a
                centered section-divider glyph within a part
  note        - optional footnote string, or None
"""

POEMS = [

    dict(
        slug="walnut-ave",
        title="walnut ave.",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "you'll never get anything",
                "as everything comes from you",
                "",
                "then turns to gold; outside the car window,",
                "mountains are breathing under invisible sun.",
                "",
                "they are sugarcoated",
                "they are the gold of a hidden dragon",
                "they are the anecdotes of the dragon long before us",
                "they are the lust for more fire in our desert",
                "they are the buried dreams of our desert",
                "",
                "they are everything in my veins",
                "as i stay here at the crossroad, walnut ave.",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="concussion",
        title="Concussion",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "Stars tingling over the steep cliffs",
                "of my arms. At the borderline of table",
                "this morning, an event clicked,",
                "beyond reach.",
                "",
                "Miscarriage of an apple makes life quit",
                "even harder.",
                "We ponder on how pure magic can be poured",
                "from a withered spoon",
                "through which, fish oils glittered in sorrow.",
                "",
                "As if it was originated to be uncontrolled.",
                "As if we call fallen apples cowardice.",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="drive",
        title="drive",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "\tto nowhereville\t\twithout",
                "a driver\t\tor is this life even possible",
                "without it\t\ttee tee daa",
                "fire of my loin\t\tof cosmos",
                "\the murmurs",
                "\t\tin the backseat",
                "sweating trembling — then",
                "\tthe book drops\t\tand destiny",
                "is handed to\tan explosion",
                "\tpassing Francesca through:",
                "",
                "sometimes she forgets",
                "\tshe could also drive",
                "\t\tin the autopilot mode",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="love-is-a-many-splendored-thing",
        title="Love is a many-splendored thing",
        subtitle="——兼幸福论",
        epigraph=None,
        parts=[
            dict(label="1.", lines=[
                "我们把电影恰好暂停",
                "于中途，便倒头睡去。相拥于",
                "此生的迷雾里。“爱情是多么",
                "美好的事物”——任由时代",
                "巨轮肆意碾轧，任由灵魂",
                "雀跃，去取那轻巧的自由。",
            ]),
            dict(label="2.", lines=[
                "你能轻易习得夜莺的声音，",
                "那是你的天赋。天籁般婉转，却也",
                "轻易多愁善感。“爱在永无",
                "哭泣的黄昏里”——留下音韵",
                "隽永，木版画留下轮廓",
                "清透，蹦出幸福的音符。",
            ]),
            dict(label="3.", lines=[
                "秋千犁过芳草地，从静谧的",
                "旷野直到东郊公园。你比我更喜爱",
                "飞行，更景仰天空的无穷。“爱情",
                "是每一个道别的清晨”——引擎",
                "发散银翼的光泽。在能望见雪山的",
                "屋檐下，希望来得悄无声息。",
            ]),
            dict(label="4.", lines=[
                "故国神游，你竟也有些触景",
                "生情。三江汇流，暗涌着原始的",
                "命脉，正如我们一无所知的抵达。",
                "“爱是永无止境的夜晚”——本以为",
                "这里的星空会更为浩瀚。于是我们",
                "在湿漉中走着走着，就梦到了外星人。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="taibai-in-conshohocken",
        title="太白在康斯霍肯",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "再回到宾州，是否仍是侠客？他大谈年轻时的游历，酒水单",
                "藏匿着的身外身。太白，或是台北？谐音穿越今古，服务生",
                "安利了一支本地的酒。觥筹交错，过往有如灌木般无关紧要。",
                "他想起开去拳馆的路边，那群白尾鹿已经变得和冬天一样冷。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="pindaros-inn",
        title="品达罗斯旅馆",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label="一", lines=[
                "我也曾热衷于去拟合那段丝般的线，在宇宙金色的边缘，",
                "行星环绕出璀璨的陷阱。斯巴达搭载永动机跑去，",
                "又悻悻离开；那片星系没有轨道，唯有幻影，唯有蓝墨色的海域。",
            ]),
            dict(label="二", lines=[
                "你能否将日子写得更长？我办理登记入住，门外水波滔天，",
                "白鸽荡漾，催促着午后的光。这并非红烛罗帐，也不是",
                "想象中的希腊 —— 它无法抵达。在轻声细语里，我失去了十年。",
            ]),
            dict(label="三", lines=[
                "穷尽可能吧，品达如是说。接下来，你们便是弯下腰枚举生命。",
                "为了排解房间里的闷，我不得不起身去找橄榄树。再想起",
                "它的训诫时，我希望我已不在山中，不在暴雨之后。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="hejiayang-notes",
        title="何家洋手记",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "*我们租用下墓园的清晨，以唤回必要的约定。*",
                "",
                "从广袤的布置中醒来，天色还淡。何家洋的",
                "公路，早于清早已通往昂贵的公墓。",
                "犬吠深处，轮回如同往常，被惺忪地路过。",
                "",
                "我从后座下车，跨过松垮的田地。",
                "垃圾焚烧，打磨出冰薄的远山。三菱重工",
                "萎蔫。旁有机警的鹤，主持际遇的沼泽。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="dongchuan-road",
        title="东川路",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "街灯下是成排走失的红树  翩翩的蝴蝶",
                "死亡是一件玉佩  在骑车人的颈上添来",
                "一场翻飞的沉重  四散的水滴构不成一场雨",
                "构不成这两者  它们仅沾惹磨旧的镜片和女孩",
                "",
                "泛光的路面书写出篝火  一册水墨电话簿",
                "在波纹逐渐合拢后归入同一个洞穴",
                "没有多余的烟和平静  升入十一点的幽光",
                "空空回转的机械  燃耗十一点的肾脏",
                "",
                "不受欢迎的商店和身体  无数歇业的眼睛",
                "扯下一袍银丝绸  赚取一个被遗忘的期限",
                "忙碌的是仪式的世纪  是粗鄙的萤火",
                "铜板在两掌中闪耀地交换  要我含住风中寒冷的舌头",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="chto",
        title="Что",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "“Нет.”",
                "“Что нет?”",
                "",
                "什么? 有什么，坚固深涩的",
                "竟会理会我，那我所熟识的",
                "什么?难道，幸存者终于音节过夜",
                "——清早醒来的人们拆除闹钟",
                "\t垫脚的石头伏在窗前",
                "",
                "什么?不，我不在溢出的对面",
                "我在自然的体内，由你裁决，",
                "这局躲藏的胜负——零:零",
                "\t我想起一部同名的诗集*",
                "\t\t有什么，在桥头悄然回归",
                "",
                "什么?不为什么，我收回",
                "衣衫的情动，寒冬招揽的",
                "一亿名陌生人。难道它不能满足",
                "\t我双重的想象——走过的人们",
                "\t\t在飞机的倒影里细数波纹",
            ]),
        ],
        note="*诗集指莫斯科女诗人 Tatiana Shcherbina 所著的《The Score of the Game》。",
    ),

    dict(
        slug="message-on-a-rainy-night",
        title="雨夜来音",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "有一拨人从睡梦中传回问答",
                "有一拨人在山的那头讲出山的迷信",
                "她的门敞开 失修的风狂呼不止",
                "磨损的阶梯通往船桅的青苔",
                "掩口的薄雾透出阀门上的字样",
                "一个平白的雨夜 如飘浮一通不定的",
                "远程电话 山岗失守来去的忙音",
                "如燕子衔回山泥的信件 一对垂钓的瞳孔",
                "如染上鱼形的纹身 睡入一湾陈年的水渠",
                "我紧抱完好的枕头起身 确认旧影依旧在手边",
                "黏湿的手心碰脏了绘本 像是有人",
                "给摆在雨天的床头柜上 没有声响",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="glass-ink-tears",
        title="玻璃·墨水·眼泪水",
        subtitle=None,
        epigraph=dict(
            lines=["只有海留存下这传奇的影子。"],
            attribution="哈特·克兰，《在麦尔维尔墓前》",
        ),
        parts=[
            dict(label="一", lines=[
                "她乘光，栖居于玻璃球内",
                "用脐带的晶莹",
                "来预见，一艘驶自阿根廷的商船",
                "",
                "她肚子里的那条蛇，翻腾地",
                "撕咬新婚洁白的纱裙",
                "血红的裙裾，掀下了十个月份的不忍",
                "",
                "也只有在十朵玫瑰的喘息中",
                "她才是母亲，并从镜中端详，",
                "梳妆台上，玻璃苹果",
                "顶梢的那抹红绿",
                "",
                "囚禁于夏夜 湿热紧致的浴衣",
                "囚禁于客厅 擦洗完毕的欲望",
                "",
                "床头柜边，一盒《泰坦尼克号》卡带",
                "在失语的钟点跟着沉没",
            ]),
            dict(label="二", lines=[
                "他踱步上码头，穿梭于",
                "各地的工艺品集市，试图在",
                "泥泞的方言中，寻找一只鸽子",
                "",
                "一组马戏团在凹凸的红布面",
                "跳跃，他推开漆黑的铁门，",
                "只见船闸，不见灯火",
                "",
                "对着太平洋的落日思索，",
                "他掏出微温的皮夹，口袋掉落出",
                "一张被海风吹咸的信纸",
                "",
                "“亲爱的…”淡淡化开的署名仿佛",
                "降落入星河，远处的海鸥飞旋至近",
                "",
                "那个人栽下朦胧的果树，举起椰子",
                "喝下了海",
            ]),
            dict(label="三", lines=[
                "假若他在餐桌上重提过往",
                "假若每逢傍晚必须流泪",
                "",
                "回答一个必答的国度，",
                "回答你刺人的胡渣，傲人的黑发",
                "和高卢人的良种烈马",
                "",
                "吊灯在不停旋转着...",
                "丝巾挂上放有樟脑丸的衣橱，敞开",
                "\t露出玫瑰",
                "",
                "我踱步上码头，捡起远方的桥",
                "眺望白色的仙子",
                "和广阔的生命——",
                "",
                "“只有海留存下这传奇的影子。”",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="endangered-afternoon",
        title="濒危的午后",
        subtitle=None,
        epigraph=dict(
            lines=["有人回忆那些建筑。"],
            attribution="史蒂文斯",
        ),
        parts=[
            dict(label=None, lines=[
                "我想是的  那些紧随的模仿者  得学会从帽子的宽沿中收回影子  作响的鞋板  终登不上风格的台阶",
                "",
                "一轮放纵后的草地上  一轮渐行渐远的邮船前  那些纤弱的爱奥尼亚柱  陡然间变得巨大  一如阳光分作古典  注进宽敞的衣束  石质的肉体泛出上升的光泽",
                "",
                "同样是濒危的午后  尺规般的形体  跌落自金融大厦停满电瓶车的街边  人细数手中的扑克  我在一次行驶中又看到海浪的脚注  那些沉重的珊瑚在轻质玻璃柜内被光刺痛",
                "",
                "我想是的  从坍圮的午后可一直书写到黄昏  人在画架边将获得永久性纪念",
                "",
                "摇摇欲坠的鸽子笼  穿梭的公文包和紧绑的领口  水晶表面反射光斑  蒙昧的蓝宝石自愿返归大海  至少 一座怀抱橄榄树林的岛",
                "",
                "同样是濒危的午后  嗑瓜子的人断续吐出闲碎  冗杂的布料无心裁出希腊式样  闪烁的电子显示屏后  有一种确信同大楼的阴影一齐落向了我",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="art-student",
        title="画生",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "他笑中带涩，说，",
                "“要考上清华美院，文凭上敲的章",
                "就是清华的。” 骄傲",
                "如一场未遂的策谋，终于僻乡",
                "堆砌满石膏与木架的阁楼烂尾",
                "那时放课后，一辆落拓的",
                "丰田将疾速在狭窄的宁穿路发飙",
                "举起手枪的人在法国梧桐的",
                "连绵中，涂下空隙间兑水的藏青",
                "一篮翕动鼻翼的夜明珠，仍保有",
                "孩童的完好，和安宁的视线",
                "车过邱隘镇，我明白自己",
                "是这里一个名正言顺的偷渡客，",
                "正频繁来返于，画家冒名的归属地",
                "姑且，称作那片白桦，坑洼小径旁的",
                "必经之所。漫长的午后，",
                "乡村别墅面朝乌云下闷热的布景，",
                "殷勤的女主人住下房间的光亮",
                "我犹能记起，那不远处偶尔跃起的",
                "几个黑点，和进出的几个没有色彩的人。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="cross",
        title="十字",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "屋子里的人正在熟睡",
                "不远的牲畜棚，青烟腾起",
                "",
                "从滑梯下来，瘦弱的男人",
                "屁股着地，弄折了十字",
                "",
                "“对我来说，哪里都是天堂。”",
                "他循着丘陵，一颠一跛",
                "",
                "大地的盆骨松弛，发白的",
                "种子，挨着跌入幽黑的裂缝",
                "",
                "他把褂子铺在旱地，收起几具",
                "\t鸟儿玲珑的尸骨",
                "",
                "田埂上，医生盘坐在救护车顶",
                "马匹一动不动，念出我的名字",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="blue-sky",
        title="青天",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我划下颧骨，安放入一只",
                "百灵鸟。割碎的酒瓶",
                "渣子，流涎和一整条不明道路",
                "",
                "骨头，在多重的脸颊",
                "抛接。表情",
                "于雾中坠入河流",
                "",
                "身下钻营的狗，东西颠倒",
                "一尊尊油腻的中原佛像",
                "碰杯并且交欢",
                "",
                "母亲，书包连着那袋红枣，",
                "我都给丢了。青天下，",
                "行人踏断了直尺",
                "",
                "我搀扶高贵的椅背，怀着",
                "清醒的呕吐——",
                "",
                "摁下电梯的大厅按钮。",
                "",
                "看胭脂无声的零落，",
                "看所有的荒唐，沉入池水。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="ideal-exile",
        title="理想流放",
        subtitle="——为奥·曼读诗会而作",
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "室外的广袤远甚于言语，一群",
                "芳香洁净的姓名纵地翻过低矮的槛",
                "接受晚风纵横的吹拂，夹杂着的",
                "远东的暴雪，此刻已不再有寒意",
                "",
                "在从未驻足的天台轻抚想象的马",
                "在烟囱之上我们互相围拢，抵御",
                "中央散放的书籍且当作蜡烛，",
                "有一种好奇被灯光照亮了一半",
                "",
                "青春的声音不显得匆忙，交织",
                "与遥远的涅瓦河面，冰层解冻的细响",
                "没有额外的世纪可供我们进入",
                "自愿拷上镣铐的人，离开他的房间",
                "",
                "从手中的发光屏幕抬起头，我的脊柱",
                "浸入平行的负片，泛白的乌云缓缓挪移",
                "我想，今夜的符拉迪沃斯托克",
                "也必定会同样落满了星星",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="wittgensteins-ladder",
        title="维特根斯坦的梯子",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "&",
                "",
                "一如男人和女人对乒乓球",
                "有不同的界定",
                "我们都有无法被译介的苦楚",
                "光线清晰泻下，",
                "一如梯子疲软地搭向桥岸",
                "维特根斯坦",
                "信写出界的蓝皮书，于此孤坐",
                "",
                "&",
                "",
                "对视中我听辨不出喑哑",
                "或许于我的口腔，或许于你:",
                "沙盘上匍行的汽车，",
                "失去鸣叫",
                "",
                "&",
                "",
                "“人该是幸福的。”",
                "确证为哑谜，为书袋底响动的",
                "蟋蟀。我们毕生蹲守于",
                "彼此翻尽的书页，",
                "——不必言说",
                "仅润湿双唇以示爱慕",
                "",
                "&",
                "",
                "目及对岸，木梯留滞于",
                "踏空的崖缘",
                "我们仍热衷于为彼此的反面施工",
                "在借与用的图纸中，",
                "他终担不起开口的代价:",
                "于乡间的木屋醒来，",
                "维特根斯坦",
                "证明了自己不会说话",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="linen-tote-bag",
        title="麻布手袋",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "在莫斯科的莫斯科书店",
                "开着暖气的柜台墙上",
                "挂售麻布手袋",
                "用它装书 或晚灯下飘着的",
                "密密的雪",
                "我用简单的英语",
                "挑选了一个中东样式的",
                "为一段下雪的行程",
                "为几本简单的书",
                "它们并不轻 而且",
                "与莫斯科没有关系",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="questions-and-answers",
        title="问答录",
        subtitle=None,
        epigraph=dict(
            lines=["那时有深不可测的水吗？"],
            attribution="《无有歌》",
        ),
        parts=[
            dict(label=None, lines=[
                "午后 他递来一只宽口的马克杯",
                "有鲶鱼的重量 在阳光立面下滑动",
                "",
                "僧侣与春风跌荡的裙摆 敞开默读",
                "草场上立起 原初的牲畜",
                "",
                "那时 莲花杀人 不还给你",
                "再多的一句",
                "溪流在我们之中无所适从",
                "",
                "我帮他平整桌布最后的皱角",
                "好像是被谁落下的 黯淡的魂魄",
                "",
                "那时 炊烟还未升起",
                "对角线上的伏击 还未引起人们的注意",
                "",
                "溪流在我们之中无法立足",
                "因为水有水的舞动 无法听入 连成线的耳朵",
                "",
                "午后 他伸出一双手 要和我交换",
                "印刻有胎记的立面 阳光 走出深度的矿藏",
                "\t滞留在原初的杯沿",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="prelude",
        title="序曲",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "地面上是我的骨头",
                "林立呈现锥形",
                "地面上是无谓的血 被后来的鸟咳出",
                "地面上有楼上的恐怖",
                "是一次无谓的降落 仅仅一次",
                "",
                "黑夜击落了栖息的黑鸟",
                "黑鸟栖息于打翻的谶语",
                "",
                "无边的寒冷的音乐",
                "我的乐器 还在我的手指间",
                "在持续许愿的天地间",
                "",
                "铃铛作响 一辆马车前往明亮的去处",
                "你有无谓的前方还有我的骨头",
                "仅仅是在最后一天前",
                "乐手停止了练习",
                "",
                "琴箱横亘于松林 呜咽童年的曲调",
                "地面上有天空断续的妆容",
                "地面上有干枯的泪的谱写",
                "即使我的手里并无音乐",
                "",
                "露水在天空寻找归处",
                "我与你并无什么不同",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="letter-to-miss-o",
        title="给O娘的信件",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "背后的房门拴住了我的气球",
                "一群糖果从苦力三轮车上跳落下台阶",
                "橙子，橙子，锁住的月亮",
                "以情趣肆虐的木马，来回如钟舌般晃动",
                "滴答，滴答，一间冰凉的作坊",
                "O 娘，我与你仅隔一个潮湿的仰角",
                "和一架沉没的钢琴，",
                "而我的灵巧能使杀人的青砖发声——",
                "",
                "就在你今夜相似却不相同的整圆",
                "就在你金色的赤裸与金色的沉默",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="wedding-chronicle",
        title="新婚纪事",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "屋檐下人们谈起婚姻的同构，像是来年的一盏明灯",
                "系于一户水上的家庭，砖瓦间的阴晦差别不大",
                "院落腾起一股春日的热气，进进出出的闲杂人等",
                "和发颤的桑塔纳车，迎娶一位鞭炮唇齿间的幸存者",
                "郊区的公主。家中的狗卧在另一处田埂上休憩",
                "远处新建的小区跨进新的安逸，待安装的窗户",
                "瞪着空洞的眼睛，接待成群的来客，他们践踏着",
                "幼嫩的钢筋水泥和刚刚成形的谎言，却把温热的红包",
                "贴往墙上最惹眼的那道疤痕，打算未来某日挂上一副",
                "凡·高的赝品，使向日葵与宛若石膏的生活相映成趣",
                "沙发随迟缓的时间硬化，两人并肩坐下，便不会再有",
                "重力的柔软。房间里的每台电器嗡嗡鸣叫，宣布一次",
                "受潮的集体逃离，从瓶罐封存的往事，从床边塌陷的多余",
                "“远方的大海漂浮满记事本与花瓣”，车辆驶过，掀起",
                "令人窒息的尾烟。一阵啼哭降生在水里，褪落的围墙间",
                "差别不大，于是便掐紧怀表，等年岁背后的那盏明灯，",
                "等彼时明亮的玻璃窗下人们谈起婚姻的同构",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="petersburg",
        title="彼得堡",
        subtitle=None,
        epigraph=dict(
            lines=["“我回到我的城市。”"],
            attribution="曼德尔施塔姆，《列宁格勒》",
        ),
        parts=[
            dict(label=None, lines=[
                "彼得堡，我认出你的性格",
                "当我陪同你的罪犯，步入辉煌的地底",
                "铁栅门生长出阴绿，遗失",
                "指南针的侏儒，携包窜进飞驰的监狱",
                "石灰落上迈步的皮草，一点缓慢的",
                "虚荣，隔着烫金的画框，",
                "我听见过道的提琴手",
                "谋划在今夜流浪",
                "",
                "彼得堡，有无数个黄昏正被煽动",
                "蝴蝶趟过积水的泥泞，天空在雪的反面燃烧。",
                "马雅可夫斯基站满载小丑，",
                "谁会是第一个主角？",
                "揭下荧幕镜的隐喻，享用一杯暖和的咖啡：苏维埃",
                "这一次，西里尔字母有话要说",
                "",
                "彼得堡，整个欧洲还剩下什么？",
                "我在冰冷的月亮下问你",
                "暴风雪摁响门铃",
                "轻拂去煤灰，拂去人的头骨",
                "在铲雪车的底下爬行，在莫伊卡",
                "黑色的血凝固的河面上悄悄地来去",
                "化身为鸽子的将军，在冬天裸着",
                "上身，牵一瓶伏特加起舞",
                "开始同样的节目",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="rainbow",
        title="彩虹",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "咸涩的湖中有明亮的风景",
                "一幢湿透已久的屋子",
                "容不下一个咆哮的男人",
                "",
                "先生，我等那个时候",
                "河流把人们一分为二",
                "一把剪子穿过了它",
                "",
                "渗出一滴街对岸的泪珠",
                "电视机搅合哭泣的信号",
                "无人知晓，黄昏以后的事",
                "",
                "黄昏以后，薄荷叶存入",
                "明日的冰柜，我跨上香槟色的",
                "单车，在手帕上骑行",
                "",
                "永远到家的后头",
                "巷子里的人缓慢如夕阳",
                "残忍如链索",
                "",
                "天国的马车从未按约出发",
                "我把安全帽当凳子坐下：",
                "在所有的道路中，我选择彩虹",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="rice",
        title="大米",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我把手伸入厚实的大米",
                "一堆粉一样的大米",
                "一堆流热汗的大米",
                "一堆秤杆边脱衣",
                "视而不见的大米",
                "以读罢昨夜的牡丹",
                "以唤回性欲",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="ren-hang-a-kind",
        title="任航一种",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label="一", lines=[
                "在海水中你看不出",
                "一具澄澈的尸体",
                "尸体过于澄澈",
                "时间过于澄澈",
                "不过",
                "有只碧蓝的鸟",
                "飞过",
                "从一团揉皱了的",
                "海水中",
                "看到湿漉漉的",
                "你",
            ]),
            dict(label="二", lines=[
                "我会抱住一片下落的草丛",
                "接住它",
                "借一束镁光",
                "讨今晚的第一支烟",
                "",
                "我会抱紧抱紧你的我",
                "寓言在孔雀的孔中",
                "沼泽在水里",
                "",
                "涨红的性器宛若田地里亟待收割的庄稼",
                "飞行中的飞机舱门打开",
                "走出一个男人",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="tonight",
        title="今夜",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "母亲为我系上红绳结",
                "母亲为我戴上戒指、太阳和月亮",
                "大伙勒令我摘下它们",
                "埋入今夜的花圃",
                "今夜的花圃",
                "静悄悄",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="study-on-a-dancer",
        title="STUDY ON A DANCER (OR TWO)",
        subtitle="——给 S.F.",
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "她们把手轻搭在，斯大林撅起的半身像上",
                "她们的蓝气球，正央求一名名复数的观众",
                "（间歇中，我目睹念珠于漏光的中央",
                "细数出一滴不剩的泉水）",
                "往高跟系带里塞入熟透的纸张",
                "（我穿行过本该避免的街道，",
                "揽客的人将地板消融，切换出音响）",
                "椅子娴熟地瘪下，或撤离，显出纷乱的拼写",
                "",
                "只有我无处安放，一幅署名德加的",
                "速写，于正面的吧台上立体",
                "那一个人端来冰桶，脖颈上淌下",
                "想象的吻（比对三双赤裸的脚踝，笔记上",
                "倒挂隐秘的印度）",
                "我知道，我们并没有在闹市的一家寿司店",
                "相识，因为笔下孱弱的线，仍在冬夜",
                "决绝的脚尖下，颤喘不已",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="eros",
        title="爱神",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "在泉水下面，树叶落满了我们",
                "天使垂下眼睑躺着，是否拥抱得太久？",
                "阳光明亮而又酸楚，我们交换了礼物",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="obituary",
        title="讣告",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "在荒凉的季节，例行的死亡",
                "就是节日的最后一抹狂欢",
                "就是最后一支断在风中的蜡烛",
                "在半山腰上数落着陨星",
                "",
                "它比一个世纪的野蛮更为长寿",
                "而正因如此，我才不忍走进那",
                "黑如墨点的雨，回头去望",
                "一整条街道上空无一人的脸",
                "",
                "飘落的黑纸盖上了乌有的风景",
                "啊，文明人的死",
                "竟也如此粗暴，甚至",
                "来不及扫进畚斗，再倒掉",
                "",
                "所有冷去的方框和石碑",
                "被荒凉的风奏响",
                "每一起几千公里外的失踪",
                "每一天熟悉不过的头条",
                "每一个人的死",
                "都加在他的死上",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="one-day",
        title="一天",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我按住我沉默的",
                "太阳穴 那里蜷着一只",
                "沉默的兔子 身上只剩下",
                "一具身体 毛茸的心脏",
                "微弱地跳动",
                "",
                "哪一天 他们担着架子",
                "收走了我的书籍",
                "兔子就钻进门前的",
                "花地 再也不出现",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="bressons-pen",
        title="布列松的笔",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "布列松的笔还在燃烧",
                "替代了沉重的蜡烛",
                "烛油滴落在巴黎黄昏的白纸上",
                "",
                "布列松的笔注视着行人",
                "行人的孤影 行人的交媾",
                "行人的脸 像巴黎的雨一般飘落",
                "",
                "布列松的笔比绝育的镜头",
                "更沉重，沉重的光线",
                "快要把它折断",
                "",
                "一个人架起一生的幸运",
                "一册影像在雨天重获姓名",
                "把受难还给一个老人",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="throw-away-the-book-and-go-out",
        title="抛开书本上街去",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "你漂浮着如",
                "深蓝色充气的",
                "床垫 认真地",
                "对着渔网",
                "手淫",
                "",
                "想象",
                "一摞受潮的杂志",
                "封面 古铜色",
                "已不再新鲜",
                "",
                "便宜的",
                "电子手表 准确预告了",
                "一个人体艺术的",
                "下午",
                "",
                "你在 轮胎之中",
                "扑腾",
                "而它径自 蒙上了灰",
                "在离岸不远的深处",
                "",
                "在墓石垒的",
                "缝隙  每一篮",
                "螺蛳的潜伏之地",
                "",
                "蚊虫 涉过水面",
                "你漂浮",
                "在被阳光遗漏的",
                "水域",
                "",
                "那里的温度",
                "比来世更低",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="ferry",
        title="摆渡",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我在渡口排队的时候，看见",
                "滩涂的螃蟹，分捡晒干的葡萄",
                "和人们丢下的烟头。",
                "当地人拎着腥味的大小包裹，消失在",
                "异乡的口音中，像黄色海风下",
                "黄色的海。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="dear-sylvia",
        title="亲爱的西尔维娅",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "亲爱的西尔维娅，我并不害怕",
                "蜜蜂，它们的吵闹",
                "使我常常忘了我是一个人",
                "",
                "西尔维娅，你留下最后一顿",
                "早餐后，把所有锋利的",
                "消息都丢给了我",
                "",
                "现在，我要拾回你的手帕和祈祷，",
                "驮回你深处滚落的煤球",
                "",
                "西尔维娅，",
                "在波士顿柳街，",
                "我雪天的靴底踏脏了你",
                "白色的床垫",
                "",
                "但你知道，我无法表露",
                "过多的歉意，舞会",
                "散后，钟声回荡在雾里",
                "",
                "西尔维娅，你别走，",
                "我们还有一局摊开的占卜",
                "我们还要继续闭紧眼睛",
                "游戏还未结束",
                "",
                "亲爱的西尔维娅，天黑了",
                "当所有的声音",
                "走后，我只有你",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="too-many-good-things",
        title="人们不允许太多美好的事物同时发生",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "人们不允许太多美好的事物同时发生",
                "就好比，在清晨，她吓唬了自己",
                "戴着口罩，自陌生处",
                "",
                "横过一柄榔头，把蒙上呼吸的",
                "镜子击得粉碎",
                "",
                "太多美好的事物总是碍事，",
                "美梦挨着美梦从楼梯上",
                "纷纷跌落",
                "",
                "笨拙的新郎总会踩住",
                "大小姐的裙摆",
                "",
                "天鹅，撅嘴朝向",
                "骑着自行车的小男孩",
                "",
                "进攻。人们好像",
                "不喜欢太多美好的事物",
                "",
                "美好，使得他们厌烦",
                "他们不妒忌美好，",
                "只是妒忌太多",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="poets-genes",
        title="诗人的基因",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我光辉的父辈们，",
                "诗人的基因在他们身上",
                "它表达为",
                "烟鬼、秃顶，",
                "和轻微的精神分裂症",
                "并把整个后脑勺的忧郁",
                "像丢烟蒂一般",
                "丢给了我",
                "",
                "但我清楚 他们是诗人",
                "即便他们不写诗",
                "即便他们摇晃起身子",
                "行走在雨中",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="anecdote",
        title="轶事",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "在刚积起雪的院子里",
                "搬一把竹椅，围成一个圆圈",
                "八卦起那位戴雷锋帽的",
                "老酒包，比如，打探他年轻时",
                "如何，在灯下",
                "索求她的一枚吻",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="she",
        title="她",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我轻轻地抚去她的尘埃",
                "她正坐在云朵陷落的地方",
                "",
                "有时，她那双白色体操鞋",
                "认出了我黄昏的信物",
                "",
                "鸟儿便衔着闪光的树枝",
                "领她回到落满尘埃的相框",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="love-poem",
        title="情诗",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我无法爱你，",
                "就好比",
                "云朵与云朵的分歧",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="for-zhong-fang",
        title="给钟放",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "死亡",
                "总归不同于诗里的死",
                "句子里的死，",
                "总像只猫",
                "",
                "过分庞大的",
                "盐粒，终于在这个黎明",
                "析出",
                "",
                "钟点敲响，",
                "碰巧，新车的里程数",
                "碰见北京灰蒙的雨",
                "",
                "傍晚，赶集的人",
                "携有不同于清早的目的",
                "",
                "沉默总比天使留得更久，",
                "过多的道别把我们消耗殆尽",
                "",
                "孪生的忧郁，在别处快活",
                "绵软的手心，肉体的大海，",
                "容下每一行悸动",
                "",
                "“一个诗人的死从来都不高级”",
                "死亡被眈眈许久",
                "只躲进露水草丛",
                "",
                "火化的",
                "医疗用具，从来都不是",
                "那缕登上王座的烟",
                "",
                "你，圆圈的",
                "出走者，终于返回这",
                "肥胖的子宫",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="no-one-sets-out-with-me",
        title="没有人和我一起出发",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "没有人和我一起出发",
                "马匹低头只思索自己的逃亡",
                "一个雪天 一座悬崖也没有",
                "没有一个人的领口",
                "勾在梳得柔顺的新月上",
                "",
                "没有人和我一起出发",
                "没有人要把流浪向我倾诉",
                "没有人还留着旧居的墙砖",
                "怀揣在口袋",
                "一个人也没有",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="if-on-a-winters-night",
        title="如果在冬夜",
        subtitle=None,
        epigraph=dict(
            lines=[
                "我爱上一个女孩，她有梦游症",
                "常常在月亮下对着一口油井梳头",
                "在我午睡的时候，她站在窗前咬自己的指甲",
                "她指甲油的红色让我的梦焦躁不安",
            ],
            attribution="昆鸟，《历程》",
        ),
        parts=[
            dict(label=None, lines=[
                "忧郁积在我的门口",
                "厚厚的，有一个小孩那么高",
                "我推不开年月已久的这道铁门",
                "在这个纷扰的冬夜",
                "",
                "大雪中，",
                "我失去了我的雪人",
                "她鼻尖冻红的胡萝卜色",
                "曾领我回到出走的家乡",
                "",
                "那一年圣诞，她把一只",
                "包装在好看的塑料盒子里的",
                "青苹果丢给我，",
                "对于苹果",
                "我是不爱吃的",
                "但我却皮也没有剥去",
                "更没有淋洗",
                "就咬下了她的心意",
                "",
                "如果在冬夜，我解开了",
                "蛇形的锁链，在冬夜",
                "鲜花从不会入眠",
                "",
                "在冬夜，所有的钟摆",
                "都催促着",
                "晚到的时间",
                "在冬夜，晚点的商店",
                "空无一人",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="glass",
        title="玻璃",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "女人 男人对于内心",
                "玻璃的一次素描",
                "玻璃从所有纹路长出",
                "大于肉体的总和",
                "大于晶莹的疼痛",
                "",
                "一棵柳树 扬起不计后果的风情",
                "冬天 橱窗 血结了痂",
                "我所能看见的 只有我的黑色",
                "大于康复的药膏",
                "大于凝重的眼睛",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="poem-of-connections",
        title="关联之诗",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "我要怀抱金鱼",
                "我要喃喃自语",
                "面对一篮水果，在桌子上",
                "整整齐齐",
                "我要梳理身体的每一寸",
                "不毛之地",
                "我要扯断风铃",
                "我想要回我的手套",
                "我希望有另一张面孔替我老去",
                "我还想再见一见那匹犀牛",
                "不是尤内斯库，",
                "是我自己",
                "烟灰缸里卧着的金鱼",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="it-has-a-color",
        title="它有，但我们要说出它的颜色吗？",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label="一", lines=[
                "你的海与我的海重叠",
                "你的浪头冲翻了我的调色板",
                "你不允许我的蓝色涂上你的沙滩",
                "你轻巧的小脚搭在我的肩上",
                "想要够到蓝色",
                "想要我在我的蓝色里溺亡",
            ]),
            dict(label="二", lines=[
                "围坐在公园里的人慢慢生锈",
                "摊着舌头的狗在群像边奔走",
                "至少冲突的颜料",
                "能在飘满腥臭的水里溶解",
                "",
                "最好，景观都用肉色作底色",
                "让每一分秒都感受到疼痛",
                "衣服，那是用秒针都能戳破的",
                "夜空用一罐藏青就能解决",
                "",
                "冬天，一根魔杖抵御空白的雪花",
                "你不能看到没有五官的脸",
                "喂，用一箱泡沫喂饱它",
                "用五颜六色的贴纸贴满整个宇宙",
            ]),
            dict(label="三", lines=[
                "感谢品尝颜色的画家们",
                "感谢道尔顿和礼物袜子",
                "感谢机灵的狗和红色的树",
                "感谢那一次从无到有的上钩",
                "所以",
                "",
                "它有，",
                "但我们要说出它的颜色吗？",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="dog-radical",
        title="反犬旁",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label="一", lines=[
                "我已准备好亲吻你",
                "猎豹将追逐无尽的潮水",
                "我随时都可以亲吻下去",
                "一丛蝴蝶将从斑马线上起飞",
            ]),
            dict(label="二", lines=[
                "“把全部的衣服拿去河流里浸透",
                "把裸着的身子贴向裸着的树”",
                "人字去掉偏旁，支起木头",
            ]),
            dict(label="三", lines=[
                "总有人会给香蕉剥去果皮",
                "总有人对阴道郑重其事",
                "",
                "一座岛屿再无法被心线牵引",
                "牢笼重归野兽的秩序",
            ]),
            dict(label="四", lines=[
                "影子它绊住脱缰的马",
                "要我躲进一朵玫瑰",
                "寸步不移",
            ]),
            dict(label="五", lines=[
                "当诗意要从阿茨海默症中追寻",
                "人立于遗忘的垃圾堆旁",
                "两只空手提着兔子",
            ]),
            dict(label="六", lines=[
                "地球原始的转动声",
                "只允许被少数耳朵猎获",
                "祖先们聚在兔子的穴中，渴望月色",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="human-world",
        title="人间",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "为什么要跪下",
                "这里不是原野，",
                "摩托却如牛羚一般侧下",
                "",
                "挣不开镣铐的名字终于变了黑白",
                "",
                "为什么又是纸在烧",
                "天下雨",
                "你本意拿伞，却拿起了刀",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="morning-glow",
        title="朝霞",
        subtitle=None,
        epigraph=dict(
            lines=["尚有无数朝霞还未点燃我们的天空。"],
            attribution=None,
        ),
        parts=[
            dict(label=None, lines=[
                "我们还未认识红色，便已将它拿来使用，把它",
                "堆上我们的画布：",
                "",
                "\t\t一道卡在两腿之间的朝霞",
                "",
                "在诗里加了点糖，嫌不够，",
                "你又提着婚礼的长裙，向他奔跑——",
                "",
                "\t\t朝霞，只单单望着，就忘了落下",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="letter-from-taoyuan",
        title="桃园寄北",
        subtitle=None,
        epigraph=dict(
            lines=["何当共剪西窗烛，却话巴山夜雨时。"],
            attribution=None,
        ),
        parts=[
            dict(label=None, lines=[
                "机翼折承，领人接回音讯。冒失的游子",
                "被快捷地安抚，矫正于标间。灯下，行李尽该",
                "归零，锃亮的马路驶过机车群。",
                "",
                "我念起蜂鸟，悬停于你松软的唇瓣",
                "上下翩舞，嗡鸣加速挑弄白足。掌道中柔，乌有之",
                "桃园簌落下熟果，惊动鼻脊下青羞的峡谷。",
                "",
                "画卷铺开，星运将缓缓熟悉我的赞叹。",
                "身体标识若浮雕，作芬芳的路面。琥珀宫囚置",
                "绞具攻心，吞吐湿濡。潮红处所绣是罂粟。",
                "",
                "你导向我以干涸，以级数的慰藉:",
                "丘陵隐忍起伏入盲区，饱满的交通放肆速度;",
                "红转绿、全城舒眉，微物自地底喷涌快乐。",
                "",
                "我将起身囊紧收拢的泉水。市中央草坪",
                "经营着长久的秘吻，捷运末站无雨无妄。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="the-right-moment",
        title="火候",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "过坎逢冬天催促，皮箱窜过街老鼠。",
                "吹笛手反穿花衣， 胡同陪槐树乞讨。",
                "荧荧分辨率拥挤，惶惶炙烤外星人。",
                "回顾长镜头节俭，高压电滋补阴处。",
                "省事人耐烦眼前，拨奏友爱的车铃。",
                "外衣袋滴渗稠蜜，几件太妃糖封喉。",
            ]),
        ],
        note=None,
    ),

    dict(
        slug="farewell",
        title="送别",
        subtitle=None,
        epigraph=None,
        parts=[
            dict(label=None, lines=[
                "当明天跟随明天的使节离去",
                "整个春天只剩下一列火车",
                "我该如何拿一朵花来望你",
                "",
                "新娘，",
                "我的白马跨不过铁道的深渊",
            ]),
        ],
        note=None,
    ),

]
